### ISSUE TITLE
Screen stays black after installing this sketch

### ISSUE THREAD

**Issue by hapklaar** [VolosR/NewTTGOAnalogReadings#2]
Hi there!

Just received 3 T-Display-S3's today and wanted to try your code. Compiling and flashing seems to go fine, but the screen stays black afterwards. Also replugging or resetting the board makes no difference. Tried all 3 modules.

Do you have any idea what might be wrong?

**Comment by VolosR** [comment]
you need to use tft_espi librari included in  orginal github rep. Here is my tutoarial how to use this board in Arduino IDe
https://youtu.be/gpyeMjM9cOU

**Comment by hapklaar** [comment]
I was already using that library, but I tried flashing again a couple of times and now it works! No idea what was wrong...
